### ISSUE TITLE
Shell file not found: self_supervised/BYOL-ACDC.sh

### ISSUE THREAD

**Issue by AloneIsland** [kaland313/SSL-MedSeg#4]
Hello,

I did not find this file in repositories: self_supervised/BYOL-ACDC.sh

What is it used for? Can you provide the file?

**Comment by kaland313** [comment]
The `self_supervised/BYOL-ACDC.sh` is no longer needed. 
To run the BYOL pretraining you need to modify the [self_supervised/configs/byol_acdc.yaml#L32](https://github.com/kaland313/SSL-MedSeg/blob/main/self_supervised/configs/byol_acdc.yaml#L32) yaml file then run the pretraining as explained in the [README's Pretraining section](https://github.com/kaland313/SSL-MedSeg/blob/main/README.md#pretraining).
